export const metadata = {
    title: 'Single Kimit product',
    description: 'Generated by create next app',
}
const Layout = ({ children }) => {
    return (
        <>
            {children}
        </>
    );
}

export default Layout;